CREATE TABLE F1 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
CREATE TABLE F2 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R1 (A INT, B INT, C INT, E INT, D INT, F INT);
CREATE TABLE R2 (D INT, E INT);
